### PR TITLE
Make monit auto-start on Debian Squeeze, as it does not do so by default when installed

### LINKED ISSUE #14: monit won't start on Debian Squeeze
Debian Squeeze's version of monit needs "startup=0" changed to "startup=1" in /etc/default/monit.

### PR DESCRIPTION
**Pull request by thatgraemeguy**
Attempts to fix #14

### CODE REVIEW

**Comment by jonhattan** [comment]
Hi @thatgraemeguy. It's better to use `versioncmp($::lsbmajdistrelease, '6') == 0` (untested). There're examples of that in params.pp

**Comment by thatgraemeguy** [comment]
@jonhattan thanks for that. I think I've updated it. My git-fu isn't as strong as it could be ;)

**Comment by thatgraemeguy** [comment]
Oh, I've kinda borked it properly..... trying to fix now.

**Comment by thatgraemeguy** [comment]
OK, I managed to squash the messy commits..... I think. ;-)

**Comment by thatgraemeguy** [comment]
OK, done properly now. No, for real this time! :-D

**Comment by jonhattan** [comment]
Merged. Thanks.

Ideally this should be extended to support Wheezy and above where START=yes|no is used instead of startup=0|1. Difference is that default is START=yes. More PRs welcome!

**Comment by thatgraemeguy** [comment]
Thanks for merging. I'll look at implementing the suggested changes sometime soon.

**Pull request merged**
