### PR TITLE
fix 'http headers' param in test-validation

### PR DESCRIPTION
**Pull request by ThomasLohner**
The param is actually called 'HTTP HEADERS' and not 'HOSTHEADER'.

see: https://mmonit.com/monit/documentation/monit.html

```
Syntax:

 PROTO(COL) HTTP
     [REQUEST "string"]
     [STATUS operator number]
     [CHECKSUM checksum]
     [HTTP HEADERS list of headers]
     [CONTENT {= | != } STRING]
```

### CODE REVIEW

**Comment by jonhattan** [comment]
Ouch. This changed in monit 5.9 - see changelog https://mmonit.com/monit/changes/

We need to identify the monit version in use, and generate the config in concordance.

**Comment by jonhattan** [comment]
Or, at least in this case, accept both params and add a comment indicating when HOSTHEADER was deprecated and HTTP HEADERS started being in force.

**Comment by ThomasLohner** [comment]
thx for the feedback. i'll fix.

**Comment by ThomasLohner** [comment]
I've added both Params and also provided a sample config for hiera in README.md

**Comment by jonhattan** [comment]
Merged. Thanks!

**Pull request merged**
