### PR TITLE
Made monit's PROGRAM STATUS TESTING work, made ACTION EXEC work, made exec path accept parameters.

### PR DESCRIPTION
**Pull request by derjohn**

### CODE REVIEW

**Comment by jonhattan** [comment]
Merged. Thanks!

**Comment by derjohn** [comment]
@jonhattan According to monit's doc you can also call a script with arguments, like '/foo/myscript bar baz'. In that case you validation would fail. I have to idea in which version of monit the argument stuff will work, in 5.6 it doesn't, the docs say it works with 5.14.
And yes, it would be cleaner to split after with the first blank and validate [0] only :)

**Comment by derjohn** [comment]
Like this: https://github.com/derjohn/puppet-monit/commit/cee133ae751ce3256f2748298994ce081b56b7c7

(untested, I will make a pull-request after I tested it)

**Comment by jonhattan** [comment]
Changed the implementation of ACTION EXEC in b071dd5ec3789f04486a78e54d06f356c522ad65

**Pull request merged**
