### PR TITLE
Added a restart_limit parameter.

### PR DESCRIPTION
**Pull request by triforce**
This adds a new parameter allowing restart tolerance to be set on a service.

### CODE REVIEW

**Comment by triforce** [comment]
Is there a reason this isn't being merged?

**Comment by jonhattan** [comment]
Ok just reviewed it. Looks fine but there're two improvements I'd like to see:

 * The thing you're implementing is called [service restart limit](https://mmonit.com/monit/documentation/monit.html#SERVICE-RESTART-LIMIT) in monit, so I'd like to name it in concordance -> $restart_limit instead of $restart_tolerance.
 * In monit a "service" is any checkable thing, not specifically a process (https://mmonit.com/monit/documentation/monit.html#Service-checks), so this config should be implemented in the common case (same as $noalerts for example).

Let me know if you're willing to do those changes. Otherwise I'll accept your PR and I'll do the changes myself afterwards.

**Comment by triforce** [comment]
I would be more than willing to make those changes and they make perfect sense it is just finding the time at the moment for me so feel free to make those changes yourself.

**Comment by triforce** [comment]
@jonhattan I have some time to sort this out now and I will also get master merged in and resolve those conflicts.

**Comment by triforce** [comment]
All of those changes requested should now be in this branch.

I will work on the master merge next where there will be several conflicts I'm sure.

**Comment by triforce** [comment]
@jonhattan that should be all of the changes required now. I have deliberately left the formatting since I think it's going to need a large overhaul on the parameters to get everything lined up correctly and you may as well tidy all of the formatting in one go across the project in a single commit to get it all uniform.

Let me know if you would like anything else changed.

**Comment by janfickler** [comment]
Hy,

only a question.
I want to use that module, but the function that you include here is that what i need.

can you explain me how i can bring this code into the puppet-style
```
 check process icinga2 with pidfile /run/icinga2/icinga2.pid start 
 program = "/sbin/service icinga2 start"
 stop program = "/sbin/service icinga2 stop"
 if 5 restarts within 5 cycles then timeout',
```
second question would be, when is this functionality in the module available.
I mean, when will the new version with this function integrated be released ?

Thank you very much :-)

**Comment by triforce** [comment]
> Hy,
> 
> only a question.
> I want to use that module, but the function that you include here is that what i need.
> 
> can you explain me how i can bring this code into the puppet-style
> 
> ```
>  check process icinga2 with pidfile /run/icinga2/icinga2.pid start 
>  program = "/sbin/service icinga2 start"
>  stop program = "/sbin/service icinga2 stop"
>  if 5 restarts within 5 cycles then timeout',
> ```
> 
> second question would be, when is this functionality in the module available.
> I mean, when will the new version with this function integrated be released ?
> 
> Thank you very much :-)

You can use the restart_limit functionality using this:
`
restart_limit => { 
 restarts => 5, 
 cycles   => 5,
 action   => 'timeout',
}
`

In terms of when this will be available in this codebase you will have to wait until my pull request has been merged.

**Comment by jonhattan** [comment]
Commits reworked and pushed to master. Thanks!

**Pull request closed without merging**
