### PR TITLE
Path validation only up to 1st blank

### PR DESCRIPTION
**Pull request by derjohn**

### CODE REVIEW

**Comment by jonhattan** [comment]
Did you test the case when path has no arguments? i.e. there's no whitespaces.

**Comment by jonhattan** [comment]
Also, I like proper naming (I spend a lot of time thinking about names!). `$pathprefix` doesn't represent what the variable contains. I prefer a more appropiate name, something generic like `$parts` also works.

**Comment by derjohn** [comment]
@jonhattan , Yeah, true, I will create another pull-request and use a better naming, indeed is $part[0] the better name for "pathprefix".

**Comment by jonhattan** [comment]
Merged. Thanks.

**Pull request closed without merging**
